-- MySQL Script generated by MySQL Workbench
-- Tue Nov 14 15:13:35 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema balance_ton_code
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema balance_ton_code
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `balance_ton_code` DEFAULT CHARACTER SET utf8 ;
USE `balance_ton_code` ;

-- -----------------------------------------------------
-- Table `balance_ton_code`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `balance_ton_code`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `balance_ton_code`.`utilisateur` (
  `id_util` INT(11) NOT NULL AUTO_INCREMENT,
  `prenom` VARCHAR(50) NOT NULL,
  `nom` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `inscription` DATE NULL DEFAULT NULL,
  `annee_de_naissance` INT(4) NULL DEFAULT NULL,
  `pays` VARCHAR(50) NULL DEFAULT NULL,
  `rang` INT NULL DEFAULT 10,
  `password` VARCHAR(128) NULL,
  `nb_article` INT NULL DEFAULT 0,
  `nb_comments` INT NULL DEFAULT 0,
  PRIMARY KEY (`id_util`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `balance_ton_code`.`language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `balance_ton_code`.`language` ;

CREATE TABLE IF NOT EXISTS `balance_ton_code`.`language` (
  `id_lang` INT(10) UNSIGNED NOT NULL,
  `nom_lang` VARCHAR(50) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_lang`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `balance_ton_code`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `balance_ton_code`.`article` ;

CREATE TABLE IF NOT EXISTS `balance_ton_code`.`article` (
  `id_article` INT(11) NOT NULL,
  `titre` TEXT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `contenu` TEXT NULL DEFAULT NULL,
  `vote` DECIMAL(10,0) NULL DEFAULT NULL,
  `date_parution` DATE NULL DEFAULT NULL,
  `utilisateur_id_util` INT(11) NOT NULL,
  `lang_id_lang` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_article`),
  INDEX `fk_article_utilisateur_idx` (`utilisateur_id_util` ASC),
  INDEX `fk_article_lang1_idx` (`lang_id_lang` ASC),
  CONSTRAINT `fk_article_utilisateur`
    FOREIGN KEY (`utilisateur_id_util`)
    REFERENCES `balance_ton_code`.`utilisateur` (`id_util`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_lang1`
    FOREIGN KEY (`lang_id_lang`)
    REFERENCES `balance_ton_code`.`language` (`id_lang`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `balance_ton_code`.`commentaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `balance_ton_code`.`commentaire` ;

CREATE TABLE IF NOT EXISTS `balance_ton_code`.`commentaire` (
  `id_com` INT(10) UNSIGNED NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `date_parution` DATE NULL DEFAULT NULL,
  `article_id_article` INT(11) NOT NULL,
  PRIMARY KEY (`id_com`),
  INDEX `fk_commentaire_article1_idx` (`article_id_article` ASC),
  CONSTRAINT `fk_commentaire_article1`
    FOREIGN KEY (`article_id_article`)
    REFERENCES `balance_ton_code`.`article` (`id_article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `balance_ton_code`.`picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `balance_ton_code`.`picture` ;

CREATE TABLE IF NOT EXISTS `balance_ton_code`.`picture` (
  `id_pic` INT(10) UNSIGNED NOT NULL,
  `caption` VARCHAR(50) NULL DEFAULT NULL,
  `image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_pic`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `balance_ton_code`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `balance_ton_code`.`tag` ;

CREATE TABLE IF NOT EXISTS `balance_ton_code`.`tag` (
  `id_tag` INT(10) UNSIGNED NOT NULL,
  `tag_name` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_tag`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `balance_ton_code`.`token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `balance_ton_code`.`token` ;

CREATE TABLE IF NOT EXISTS `balance_ton_code`.`token` (
  `id` INT(11) NOT NULL,
  `cle` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `balance_ton_code`.`article_has_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `balance_ton_code`.`article_has_tag` ;

CREATE TABLE IF NOT EXISTS `balance_ton_code`.`article_has_tag` (
  `article_id_article` INT(11) NOT NULL,
  `tag_id_tag` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`article_id_article`, `tag_id_tag`),
  INDEX `fk_article_has_tag_tag1_idx` (`tag_id_tag` ASC),
  INDEX `fk_article_has_tag_article1_idx` (`article_id_article` ASC),
  CONSTRAINT `fk_article_has_tag_article1`
    FOREIGN KEY (`article_id_article`)
    REFERENCES `balance_ton_code`.`article` (`id_article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_has_tag_tag1`
    FOREIGN KEY (`tag_id_tag`)
    REFERENCES `balance_ton_code`.`tag` (`id_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
